name: 'Skedulo Deploy'
description: 'Skedulo Deploy Actions'
inputs:
  SKEDULO_API_SERVER: 
    description: 'Skedulo Server'
    required: true
  SKEDULO_API_TOKEN:  
    description: 'Skedulo API'
    required: true
  ORG_NAME:  
    description: 'Skedulo Org Name'
    required: true
  PACKAGE_PATH:  
    description: 'Folder Deploy'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    - uses: actions/download-artifact@v3
      with:
        path: built
    - run: |
            pwd
            ls -la
            echo "🎉 run deployment"
            touch .env
            echo SKEDULO_API_SERVER=${{ inputs.SKEDULO_API_SERVER }} >> .env
            echo SKEDULO_API_TOKEN=${{ inputs.SKEDULO_API_TOKEN }} >> .env
            echo PACKAGE_PATH=${{ inputs.PACKAGE_PATH }} >> .env
            echo ORG_NAME=${{ inputs.ORG_NAME }} >> .env
            node dist/index.js
      shell: bash