name: 'Skedulo Deploy'
description: 'Skedulo Deploy Actions'
inputs:
  SKEDULO_API_SERVER: 
    description: 'Skedulo Server'
    required: true
  SKEDULO_API_TOKEN:  
    description: 'Skedulo API'
    required: true
  ORG_NAME:  
    description: 'Skedulo Org Name'
    required: true
  PACKAGE_PATH:  
    description: 'Folder Deploy'
    required: true
runs:
  using: node16
  main: 'dist/index.js'