name: 'Skedulo Deploy'
description: 'Skedulo Deploy Actions'
inputs:
  SKEDULO_API_SERVER: 
    description: 'Skedulo Server'
    required: true
  SKEDULO_API_TOKEN:  
    description: 'Skedulo API'
    required: true
  ORG_NAME:  
    description: 'Skedulo Org Name'
    required: true
  PACKAGE_PATH:  
    description: 'Folder Deploy'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: |
            pwd
            yarn install
            yarn run compile
            node dist/index.js
      shell: bash